import { test, expect } from '@playwright/test';

test('test datasets 1', async ({ page }) => {
  await page.goto('http://10.10.53.186:8090/');

  await page.locator('#menu-dataset-view-main').getByText('example').hover();
  await page.getByText('custom').hover();
  await page.getByTitle('Graphs 1\nNodes: [34]\nDirected: False\nHetero: False').click();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.getByRole('radio', { name: '2comms (2 classes)' }).check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.getByRole('radio', { name: '3comms (3 classes)' }).check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.getByRole('radio', { name: '4comms (4 classes)' }).check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.getByRole('radio', { name: 'default' }).check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.getByRole('checkbox', { name: '-hot over nodes (size=34)' }).check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.getByRole('radio', { name: 'and 33 nodes (2 classes)' }).check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.getByRole('radio', { name: '2comms (2 classes)' }).check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.getByRole('radio', { name: '3comms (3 classes)' }).check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.getByRole('radio', { name: '4comms (4 classes)' }).check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('div').filter({ hasText: /^Edit$/ }).nth(3).click();
  await page.getByRole('checkbox', { name: 'ones (size=10)' }).uncheck();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.getByRole('radio', { name: 'and 33 nodes (2 classes)' }).check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.locator('div').filter({ hasText: /^2comms \(2 classes\)$/ }).click();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.getByRole('radio', { name: 'default' }).check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-view-accept').click();

  await page.locator('#menu-dataset-view-main').getByText('example').hover();
  await page.getByTitle('Graphs 1\nNodes: [8]\nDirected: False\nHetero: False').click();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.getByRole('checkbox', { name: 'b (size=3)' }).check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.getByRole('radio', { name: 'threeClasses (3 classes)' }).check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.locator('#menu-dataset-var-view-labelings-node-regressionregression').check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.locator('#menu-dataset-var-view-labelings-edge-regressionregression').check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.getByRole('radio', { name: 'default' }).check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.locator('#menu-dataset-var-view-node-1hot-input').check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.getByRole('radio', { name: 'binary (2 classes)' }).check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.locator('div').filter({ hasText: /^threeClasses \(3 classes\)$/ }).click();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.locator('#menu-dataset-var-view-labelings-node-regressionregression').check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.locator('#menu-dataset-var-view-labelings-edge-regressionregression').check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.getByRole('radio', { name: 'default' }).check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.getByRole('checkbox', { name: 'b (size=3)' }).uncheck();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-view-accept').click();

  await page.locator('#menu-dataset-view-main').getByText('example').hover();
  await page.getByTitle('Graphs 1\nNodes: [8]\nDirected: True\nHetero: False').click();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.getByRole('checkbox', { name: 'b (size=1)' }).check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.getByRole('radio', { name: 'default' }).check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.getByRole('checkbox', { name: '-hot over nodes (size=8)' }).check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.getByRole('checkbox', { name: 'a (size=1)' }).uncheck();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.getByRole('radio', { name: 'binary (2 classes)' }).check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.getByRole('checkbox', { name: 'b (size=1)' }).uncheck();
  await page.getByRole('checkbox', { name: 'a (size=1)' }).check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.getByRole('radio', { name: 'default' }).check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-view-accept').click();

  await page.locator('#menu-dataset-view-main').getByText('example').hover();
  await page.getByTitle('Graphs 3\nNodes: [3, 4, 5]\nDirected: False\nHetero: False').click();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.getByText('threeClasses (3 classes)').click();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.getByRole('radio', { name: 'regression' }).check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.getByText('default').click();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-view-accept').click();

  await page.locator('#menu-dataset-view-main').getByText('example').hover();
  await page.getByTitle('Graphs 8\nNodes: [5, 4, 4, 8, 6, 7, 7, 9]\nDirected: True\nHetero: False').click();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.getByRole('checkbox', { name: 'b (size=2)' }).check();
  await page.getByRole('checkbox', { name: 'a (size=2)' }).uncheck();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.getByRole('radio', { name: 'default' }).check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.getByRole('checkbox', { name: 'a (size=2)' }).check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.getByRole('radio', { name: 'binary (2 classes)' }).check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');
  await page.locator('#menu-dataset-var-view-accept').click();
  await page.getByRole('checkbox', { name: 'b (size=2)' }).uncheck();
  await page.getByRole('radio', { name: 'default' }).check();
  await page.getByRole('button', { name: 'Accept' }).click();
  await page.waitForResponse('**/dataset');

});
